### ISSUE TITLE
Delta's type can't be specified

### ISSUE THREAD

**Issue by ladybunne** [marad/scalartemis#1]
Hey hey! I've started playing with your library to see if it's an adequate replacement for `artemis-odb`. I've read https://github.com/junkdog/artemis-odb/issues/260, I've looked around your implementations of things, and so far, I'm impressed! It looks really good!

One issue I've run into is that your specification that `delta` must be of type `Float` is _technically_ fine, since it adheres to `artemis-odb`'s implementation of Float, but it's quite a bit more demanding in its prevalence than `artemis-odb`'s:

```scala
// artemis-odb
world.setDelta(float)
world.process()

// scalartemis
world.update(float) // can't call without a `delta` arg - not even a default value :(
```

In my particular case I'm opting to use `scala.math.BigDecimal` as my delta type, by casting my delta source (in this case, libgdx's `Gdx.graphics.getDeltaTime`) to `double`, then putting it in a `BigDecimal`:

```scala
Global.delta = Gdx.graphics.getDeltaTime.toDouble
```

I'm mostly doing this for nicer interop with my existing position/velocity code, which is already using `BigDecimal` for precision purposes. However, due to cases like the above, and particularly this case I've just spotted within `SequentialProcessingSystem`...

```scala
override def process(entity: Entity, delta: Float): Unit = {
  // same case here - `delta` is explicitly required by abstract parent methods
}
```

...it's very difficult as a result to write code that indicates that a separate `delta` source is to be used. I'm forced to implement my system's `process` methods with your signature that forces a `delta` argument to be present. I'd also have to throw a trash value at `world.process(delta)` in order to have it compile, and _that_ feels very wrong.

All of this is to say - this would be resolved if either:

1. `scalartemis` didn't explicitly force `delta` in `world.update()` and system `process()` implementations - instead, something like setting with `world.setDelta()` and accessing through `world.delta` like `artemis-odb` would allow users to opt into your suggested delta behaviour, or ignore it if desired, or
2. `scalartemis` allowed a specific type to be provided for `delta` values, freeing up users from having to adhere to the library's _suggested_ type.

I'd consider making a PR if needed. Eager to hear your thoughts.

**Comment by marad** [comment]
Hi @archmage and thanks for the interest in my library! (you're probably the only one on earth ;))

Before addressing the issue with delta type, I'd like to discuss a bit the need to use types other than Float, since it's not really clear to me and I want to fully understand your need before coming up with solutions. I understand that you are using BigDecimals becasue you need high precision. Why do you need so high precision? Are you doing some physics simulations? 

As for your propositions, I don't like the idea of having to call `world.delta` though object indirection to get the delta in the systems. Additionaly - it is not really a better solution than just setting delta to 0 (which you said, feels wrong), since the delta would be there. Just not so visible. 

The other solution, with custom type is interesting and theoretically would be nice, but I think it would be too much of a performance hit for such low added benefit.

To be honest - I don't think there is any way that we could implement this without sacrificing the performance.

**Comment by ladybunne** [comment]
Hey! I'm using `BigDecimal` to avoid float arithmetic error, specifically within the constraints of a 2D engine with non-trivial movement calculations. I've worked with floats in the past and the maths has been really inconsistent, especially with per-frame modifications to floats that represent entity position or whatnot. I could probably get away with some manual error correction code... but from all the research I did into this particular problem, the solution that appealed to me was to use arbitrary precision data types, of which `BigDecimal` looks like the best choice.

When it comes to rendering / collision code, I'd rather be able to guarantee that there's absolutely no way float arithmetic error could be used to throw off collision calculations or go out of bounds.

I feel like this process of working outside your `delta` flow could be made easier by making `world.process(delta)` have a default value of zero, which would have no performance cost and would look way nicer. As for `system.process(entity, delta)`... I've looked at your implementations and I don't see any reason why referencing `world.delta` within `system.process()` would be any worse than what's currently there:
 1. Systems _already_ contain a reference to `world`. Referencing `world.delta` is thus not a significant departure from existing architecture.
 2. The flow of reaching `system.process()` per system places a whole bunch of individually-stored `delta` values within function calls on the stack.
 3. I'd argue that the majority systems don't explicitly care about `delta`, and by forcing them to implement a `process(entity, delta)` function, it adds a lot of waste to a codebase, while also decreasing legibility ("why is delta in this function? It's not used")

Combining points 2 and 3, your library would actually be _more_ performant if you weren't unnecessarily propagating your `delta` values throughout every single system, on every single `update()` call. Better, imo, to make the value accessible and let the end user make performance optimisations if it happens to become necessary for them.

**Comment by marad** [comment]
Hey @archmage! I'm still not pretty sure about performance implications of both aproaches. Pushing delta as float through all systems may seem like an overkill, but getting it through indirection (which you get when you use a method call) is also a performance hit. 
I guess both scenarios should be tested for performance.

I also think that if you are using `BigDecimal`s all over the place, the performance hit will not come anywhere near the delta handling logic :)

But back with the delta - I don't think doing generic stuff where you can provide your own delta into the system will be beneficial. I'm leaning toward either making the delta take default value of 0 or storing it in `World` as you suggested. I'd like to have some numeric data telling me which one of the two is more performant before making the decision. 

Would you be open to test it?
