### ISSUE TITLE
Scala and sbt versions both outdated

### ISSUE THREAD

**Issue by ladybunne** [marad/scalartemis#2]
Hi again,

The versions supported by this library are outdated - Scala with a newer version breaks according to `ClassNotFoundException`s or similar. I tried with 2.12, and had to revert to 2.11 to get scalartemis to behave.

Additionally, the sbt version listed in `README.md` is pre-1.0, which is a bit old.

These could do with updating.

**Comment by marad** [comment]
Yep, this library was created some time ago...
Would you be open to fix those issues? I haven't done Scala in a while, so I don't even know what is the current version of SBT :)

**Comment by ladybunne** [comment]
I'll see if I can find time to dig into it! 

The current versions are:
- sbt: **1.2.8**, with a release candidate available for 1.3.0
- Scala: **2.13.0**

Building projects isn't my strong suit, and I've not worked with Bintray before, but I could certainly attempt a pull request with updated versions for each.

**Comment by marad** [comment]
That would be great. I think I could update the bintray stuff after the code is updated.
